# Generated by Django 3.2 on 2022-04-15 11:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(upload_to='post_files/'),
        ),
    ]
